# Generated by Django 3.0.3 on 2020-03-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=50)),
                ('imdb_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('popularity', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='99popularity')),
                ('genres', models.ManyToManyField(to='api.Genre')),
            ],
        ),
    ]
