# Generated by Django 3.0.3 on 2020-02-29 13:47
# Custom migration file used for migrating the provided JSON to DB

from django.db import migrations
from api.models import Movie, Genre
import json


def get_json_data():
    with open('imdb.json') as json_file:
        json_data = json.loads(json_file.read())
    return json_data


def insert_json_data(apps, schema_editor):
    Movie = apps.get_model('api', 'Movie')
    Genre = apps.get_model('api', 'Genre')
    json_data = get_json_data()
    for movie_data in json_data:
        # Taking the genre out from the individual movie data,
        # since genre are many to many mapped
        genre_data = movie_data.pop('genre')
        movie_data['popularity'] = movie_data.pop('99popularity')
        new_movie = Movie.objects.create(**movie_data)
        genre_ids = []
        for genre in genre_data:
            genre_name = genre.strip()
            # check if same genre already exists
            genre_exits = Genre.objects.filter(name=genre_name)
            if genre_exits.exists():
                # Append the existing genre to the list of genre for current movie
                genre_ids.append(genre_exits.get().id)
            else:
                # Create new genre
                new_genre = Genre(name=genre_name)
                new_genre.save()
                # Append the genre to the list of genre for current movie
                genre_ids.append(new_genre.id)
        # Link the genres to the movie
        new_movie.genres.add(*genre_ids)


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_json_data),
    ]
